"""(ft):
adding user id column to travel and accomodation booking



Revision ID: 3a718b7b9495
Revises: a65b626d4a91
Create Date: 2024-02-24 18:33:44.805728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a718b7b9495'
down_revision = 'a65b626d4a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accomodation_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_accomodation_bookings_user_id', 'Users', ['user_id'], ['id'])

    with op.batch_alter_table('travel_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_travel_bookings_user_id', 'Users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_travel_bookings_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('accomodation_bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_accomodation_bookings_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
